version: "2"
services:
  papp:
    build: ./
    labels:
      - "traefik.backend=papp"
      - "traefik.frontend.rule=Host:papp.docker.localhost"
    environment:
      - APACHE_SERVER_NAME=papp.docker.localhost
      - PHP_SHORT_OPEN_TAG=On
      - PHP_ERROR_REPORTING=E_ALL
      - PHP_DISPLAY_ERRORS=On
      - PHP_HTML_ERRORS=On
    networks:
      - default
    volumes:
      # Dev only map, do not map for production, copy in Dockerfile to sandbox
      - ./:/app
networks:
  default:
    external:
      name: docker_docker-localhost
